# Generated by Django 4.0.2 on 2022-04-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_alter_produtos_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagem',
        ),
    ]
