# Generated by Django 4.0.2 on 2022-04-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrinho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='preco_final',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
