# Generated by Django 4.0.2 on 2022-07-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrinho', '0003_remove_items_pertence_pessoa_carrinho_pertence_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='endereco',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrinho',
            name='telefone',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
